spring.application.name=demo

# GitHub OAuth2 Client Configuration
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=

# Facebook OAuth2 Client Configuration
spring.security.oauth2.client.registration.facebook.client-id=
spring.security.oauth2.client.registration.facebook.client-secret=


# Google OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=
spring.security.oauth2.client.registration.google.redirect-uri=
spring.security.oauth2.client.registration.google.authorization-grant-type=
spring.security.oauth2.client.registration.google.client-authentication-method=


# Google OAuth2 Provider Configuration
spring.security.oauth2.client.provider.google.authorization-uri=
spring.security.oauth2.client.provider.google.token-uri=
spring.security.oauth2.client.provider.google.user-info-uri=
spring.security.oauth2.client.provider.google.user-name-attribute=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect